jlink:
  exe: /Applications/SEGGER/JLink/JLinkExe
stm:
  part_number: STM32H753VI
  app_hex: 170112_v01_0_17_1_170113_v01_4_15.hex
ble:
  part_number: NRF52832_XXAA
  softdevice_hex: s132_nrf52_7.0.1_softdevice.hex
  bootloader_hex: secure_bootloader_uart_mbr_pca10040.hex
  dfu_settings_1_hex: dfu_settings_7e000_v4.4.0.hex
  dfu_settings_2_hex: dfu_settings_7f000_v4.4.0.hex
  app_hex: 170086_sig_ble_nrf_v4.4.0.hex

