#!/usr/bin/env bash

# Title: Enlighten Ubuntu Launcher
# Author: Samie Bee 2023
# Description: This script has no dependencies. It will install and run Enlighten on Ubuntu from source.

# This installer is written for Enlighten 4.0.12 to be installed to Ubuntu 22
# It includes an installation of Python3.7 separate from the system install.

# Do not adapt this script for installations of Enlighten 4.2.0+
# Python3.7 support is in decline

# The ubu-py37 is to be considered a downstream distribution branch
# containing a tag + patches required to run on Ubuntu.

# It is not recommended to adapt this installer for Enlighten 4.0.18+
# Write a new one instead.

# fail on error
set -e

INSTALLPATH="$HOME/.enlighten"

if [ -e "$INSTALLPATH/completed.txt" ]; then
	# activate
	source $INSTALLPATH/pyEnl4_venv/bin/activate

	cd $INSTALLPATH/Enlighten
	export PYTHONUTF8=1
	export QT_AUTO_SCREEN_SCALE_FACTOR=1
	export PYTHONPATH="../SpyC_Writer/src:../Wasatch.PY:pluginExamples:.:enlighten/assets/uic_qrc"
	python3.7 scripts/Enlighten.py
else

	echo "Enlighten is not yet installed. Would you like to install it?"

	# This script will install files and programs necessary to run Enlighten.

	echo "Press enter to continue, or Ctrl-C to cancel."
	read null

	mkdir -p "$INSTALLPATH" 
	cd "$INSTALLPATH"

	echo "Your password might be needed for system dependencies: git, python3.7, python3.7-venv, libxcb-xinerama0, libusb-0.1-4, curl"
	sudo apt update
	sudo apt install git
	sudo apt install software-properties-common
	sudo add-apt-repository ppa:deadsnakes/ppa
	sudo apt install python3.7
	sudo apt install python3.7-venv

	sudo apt install libxcb-xinerama0
	sudo apt install libusb-0.1-4

	# clone Enlighten and internal dependencies
	git clone https://github.com/WasatchPhotonics/Enlighten
	git clone https://github.com/WasatchPhotonics/SpyC_Writer
	git clone https://github.com/WasatchPhotonics/Wasatch.PY

	# checkout Ubuntu distribution branch on each
	cd Enlighten
	git checkout ubu-py37
	cd ../SpyC_Writer
	git checkout ubu-py37
	cd ../Wasatch.PY
	git checkout ubu-py37

	# back to INSTALLPATH root
	cd $INSTALLPATH

	# try to keep subsequent pip install scripts from failing ;_;
	sudo apt install curl
	curl https://bootstrap.pypa.io/get-pip.py -o get-pip.py
	python3.7 get-pip.py
	python3.7 -m pip install numpy

	# create venv for python dependencies
	python3.7 -m venv pyEnl4_venv

	# activate
	source $INSTALLPATH/pyEnl4_venv/bin/activate                                           # Activated pyEnl4_venv
                                                                                               # .....................
	python3.7 -m pip install --upgrade pip                                                 # .....................
	python3.7 get-pip.py
	python3.7 -m pip install numpy
                                                                                               # .....................
	# install pip requirements                                                             # .....................
	python3.7 -m pip install -r Enlighten/requirements.txt                                 # .....................
	python3.7 -m pip install -r SpyC_Writer/requirements.txt                               # .....................
	python3.7 -m pip install -r Wasatch.PY/requirements.txt                                # .....................
                                                                                               # .....................
	# install conda requirements (using venv, instead of conda, for easy dist)             # .....................
	python3.7 -m pip install PySide2                                                       # .....................
	python3.7 -m pip install xlwt                                                          # .....................
	python3.7 -m pip install superman                                                      # .....................
	python3.7 -m pip install pyqtgraph                                                     # .....................
	python3.7 -m pip install crcmod                                                        # .....................
	python3.7 -m pip install bleak                                                         # .....................
	python3.7 -m pip install numpy                                                         # .....................
	python3.7 -m pip install pandas                                                        # .....................
	python3.7 -m pip install pexpect                                                       # .....................
	python3.7 -m pip install psutil                                                        # .....................
	python3.7 -m pip install pytest                                                        # .....................
	python3.7 -m pip install scipy                                                         # .....................
	python3.7 -m pip install qimage2ndarray                                                # .....................
	python3.7 -m pip install pyudev                                                        # .....................
                                                                                               # .....................
	echo "installation completed $(date)" >> $INSTALLPATH/completed.txt                    # .....................
                                                                                               # .....................
	echo "The installation is complete. Rerun enlighten_ubuntu_launcher to use Enlighten." # .....................
fi                                                                                             # Activated pyEnl4_venv
